version: '3.9'
services:
  mongo:
    image: mongo:6
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  server:
    build:
      context: ./packages/server
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - PORT=8080
      - MONGO_URI=mongodb://mongo:27017/analyticsdb
      - JWT_SECRET=devsecret_change_me
      - ACCESS_TOKEN_TTL=15m
      - REFRESH_TOKEN_TTL=7d
      - CLIENT_URL=http://localhost:5173
    ports:
      - "8080:8080"
    depends_on:
      - mongo
  client:
    build:
      context: ./packages/client
      dockerfile: Dockerfile
      args:
        - VITE_API_BASE=http://localhost:8080/api
    environment:
      - VITE_API_BASE=http://localhost:8080/api
    ports:
      - "5173:80"
    depends_on:
      - server
volumes:
  mongo_data:
    driver: local

